### ISSUE TITLE
Mathematical tests by far too tight

### ISSUE THREAD

**Issue by olebole** [casacore/casacore#504] opened 2016-10-10 12:11 UTC
Many tests are too tight and therefor fail on many CPU types. Namely, these are `tLSQaips`, `tLSQfit`, `tClassicalStatictics`, `tHingeFencesStatistics`, and `tLCEllipsoid`, which fail on x86 (32 bit), ARM64, PowerPC (32 and 64 bit; both endianesses), and S390x.

The reason is that they involve many direct comparisons of doubles, like

```
    AlwaysAssert(sd.rms == sqrt(22.5/5.0), AipsError);
    AlwaysAssert(sd.stddev == sqrt(0.625), AipsError);
```

(two random lines from `tClassicalStatistics.cc`). IMO these should be replaced by comparing the difference to some small value.

**Comment by tammojan** [comment] 2016-10-10 12:14
I totally agree. Are you willing to make a pull request?

**Comment by olebole** [comment] 2016-10-10 12:20
Not in the moment; too busy, and especially `tClassicalStatistics.cc` and `tHingesFencesStatistics.cc` have countless lines like that (the other tests seem to work differently).

**Comment by tammojan** [comment] 2016-10-10 12:23
Ok, let's leave the issue open for now. Thanks for reporting it.

**Comment by tammojan** [comment] 2016-11-07 10:31
This is in fact a duplicate of #255. Closing this instance (an easy way to get the issue count down).

**Closed by tammojan** 2016-11-07 10:31 UTC
