### ISSUE TITLE
A few tests failed when running make test as root

### ISSUE THREAD

**Issue by zhengmeyer** [casacore/casacore#770] opened 2018-08-28 09:29 UTC
The following tests failed when running as root:

99% tests passed, 6 tests failed out of 525

Total Test time (real) = 109.02 sec

The following tests FAILED:
	 85 - tBucketFile (Failed)
	 87 - tByteIO (Failed)
	109 - tDirectory (Failed)
	112 - tFile (Failed)
	122 - tRegularFile (Failed)
	123 - tSymLink (Failed)
Errors while running CTest

When running the tests as user, all tests passed.

**Comment by tammojan** [comment] 2018-08-28 18:31
Duplicate of #73 (which has been open for years..)

**Comment by gijzelaerr** [comment] 2018-10-31 09:43
closing since duplicate

**Closed by gijzelaerr** 2018-10-31 09:43 UTC
