### ISSUE TITLE
tObjectID test fails on ARM 32 bit

### ISSUE THREAD

**Issue by olebole** [casacore/casacore#986] opened 2019-12-06 19:41 UTC
When compiling on Debian for the "armel" platform (ARM, 32 bit), I get the following test failure:
```
123/456 Test #123: tObjectID ........................***Failed    0.10 sec
An unrecoverable error occurred: 
(/<<PKGBUILDDIR>>/casa/System/test/tObjectID.cc : 44) Unrecoverable AlwaysAssertExit: ((hash >> 8) & 0xff) != 0
FAIL (execution failure): ./tObjectID
```
That is a new failure; 3.0.0 didn't show that.Full build log [here](https://buildd.debian.org/status/fetch.php?pkg=casacore&arch=armel&ver=3.2.1-1&stamp=1575656629&raw=0). Unfortunately, there is not more information about the failure.

**Comment by tammojan** [comment] 2019-12-06 20:03
Is this for master, or for the 3.2.1 release? (Just for reference, they're almost identical at this point.)

**Comment by olebole** [comment] 2019-12-06 20:03
That is 3.2.1.

**Comment by rtobar** [comment] 2019-12-09 02:16
Most probably caused by https://github.com/casacore/casacore/pull/897

**Comment by rtobar** [comment] 2019-12-09 02:27
I don't access to arm32 hardware, but this might be caused by bit shifting of `char` values by 8 places and more, thus hitting UB (I didn't realise at the time):

https://github.com/casacore/casacore/blob/master/casa/System/ObjectID2.cc#L44

Casting up to uInt before bit shifting would be a solution (if this is the cause); alternatively taking the original values and shifting+masking should also work. I can contribute a patch, but I won't be able to confirm if it fixes the problem.

**Comment by olebole** [comment] 2019-12-09 07:48
I can apply the patch in Debian experimental and see whether it works.

**Comment by rtobar** [comment] 2020-04-08 04:38
This is now probably fixed via #1008

**Comment by olebole** [comment] 2020-04-13 21:36
Yes, I can confirm this. Using #1008 fixes the failure. Thank you.

**Comment by tammojan** [comment] 2020-04-14 06:44
Thanks for testing @olebole!

**Closed by tammojan** 2020-04-14 06:44 UTC
