### ISSUE TITLE
Regression: tRebinLattice fails for i386, ppc, mips, mipsel

### ISSUE THREAD

**Issue by olebole** [casacore/casacore#542] opened 2016-11-25 10:16 UTC
`tRebinLattice` fails for [i386](https://buildd.debian.org/status/fetch.php?pkg=casacore&arch=i386&ver=2.2%7Erc%2B2016.11.24-1&stamp=1480010647), [ppc](https://buildd.debian.org/status/fetch.php?pkg=casacore&arch=powerpc&ver=2.2%7Erc%2B2016.11.24-1&stamp=1480003455), [mips](https://buildd.debian.org/status/fetch.php?pkg=casacore&arch=mips&ver=2.2%7Erc%2B2016.11.24-1&stamp=1480010990), [mipsel](https://buildd.debian.org/status/fetch.php?pkg=casacore&arch=mipsel&ver=2.2%7Erc%2B2016.11.24-1&stamp=1480056944):
```
388/463 Test #388: tRebinLattice ....................***Failed    0.59 sec
2016-11-24 18:07:15	WARN	RebinLattice::RebinLattice(...) (file /«BUILDDIR»/casacore-2.2~rc+2016.11.24/casacore/lattices/Lattices/RebinLattice.tcc, line 58)	Truncating bin to lattice shape for axis 1
2016-11-24 18:07:15	WARN	RebinLattice::RebinLattice(...) (file /«BUILDDIR»/casacore-2.2~rc+2016.11.24/casacore/lattices/Lattices/RebinLattice.tcc, line 58)	Truncating bin to lattice shape for axis 1

factors = [2]
shapeIn, shapeOut = [6][3]
aipserror: error (/«BUILDDIR»/casacore-2.2~rc+2016.11.24/lattices/Lattices/test/tRebinLattice.cc : 364) Failed AlwaysAssert !rb.isPaged()
FAIL (execution failure): ./tRebinLattice
```
This did not happen with 2.1.0. The code in `lattices/Lattices/test/RebinLattice.tcc` was not changed since then, but also not the source code, `RebinLattice.tcc` and `RebinLattice.h`.

**Comment by tammojan** [comment] 2016-12-01 11:49
I cannot reproduce this on the only 32bit machine I could dig up; the test passed there. For reference, `uname -a` on this machine gives `Linux 2.6.18-nano #5 SMP Mon Mar 2 15:28:10 UTC 2009 i686 i686 i386 GNU/Linux`, with gcc 4.1.2 on Red Hat Enterprise Linux Server release 5.2 (Tikanga).

Can you provide details on your test setup?

I don't think this is a showstopper for release 2.2.

**Comment by olebole** [comment] 2016-12-01 12:15
It is Debian Sid.
I think the main difference (aside from the kernel which should not play a big role here) is that I used gcc 6.2.1. Kernel is `Linux 3.16.0-4-amd64 amd64 (x86_64)`, but the failure also happens on 4.8.0 as well as on a "real" 32-bit kernel.
I don't know whether it should be handled as a showstopper. If not, I however have to decide whether I should still provide packages for these architectures (by disabling the test). Any hint?

**Comment by juliantaylor** [comment] 2016-12-02 11:59
this will happen on a 32 bit machine with more than 4GiB of ram and no cgroups as the total amount of ram > size_t.max() in `casa/OS/HostInfoLinux.h` could be fixed by changing the size_t to `uInt64` in that file.

**Comment by tammojan** [comment] 2016-12-02 12:01
Should `casa/OS/HostInfoLinux.h` be changed just on this 32 bit platform, or should we change HostInfoLinux.h just everywhere?

**Comment by juliantaylor** [comment] 2016-12-02 12:05
uInt64 == size_t on 64 bit so changing it globally is sufficient

**Comment by olebole** [comment] 2016-12-03 10:21
I can confirm that the change by @juliantaylor fixes the problems on all mentioned platforms and also works on the other.

**Comment by gijzelaerr** [comment] 2018-10-31 10:00
If I look at https://github.com/casacore/casacore/blob/master/casa/OS/HostInfoLinux.h I don't see `size_t` being set so I guess this proposed fixed never landed in the tree?

**Comment by olebole** [comment] 2018-10-31 10:09
Looks like; also there was no PR linked here. Patch could be taken from the Debian release, however:
https://salsa.debian.org/debian-astro-team/casacore/blob/master/debian/patches/Fix-too-small-int-type-for-memory-on-32-bit-machines.patch

**Closed** 2018-11-08 08:06 UTC
Labels: 32bit/arm, bug
